root = "."
tmp_dir = "tmp"

[build]
  cmd = "swag init -g cmd/server/main.go -o ./docs && go build -o ./tmp/main ./cmd/server/main.go"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "docs"]
  exclude_file = []
  delay = 1000 # ms
  log = "build.log"
  stop_on_error = true

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"
