root = "."
tmp_dir = "tmp"

[build]
  # First change to the project root, then run swag init with the correct path
  cmd = "cd /app && swag init -g ./cmd/server/main.go -o ./docs --parseDependency --parseInternal && go build -o ./tmp/main ./cmd/server/main.go"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp"]
  exclude_file = []
  delay = 1000 # ms
  log = "build.log"
  stop_on_error = true
  full_bin = ""
  kill_delay = "0s"
  send_interrupt = false
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  log_prefix = ""
  include_dir = ["cmd", "internal"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"
